export { Tabs, default } from './Tabs'
export { TabsList } from './TabsList'
export { TabsTrigger } from './TabsTrigger'
export { TabsPanel } from './TabsPanel'
export { useTabsController } from './TabsContext'

export type { TabsActivation, TabsProps, TabsVariant } from './Tabs'
export type { TabsController } from './TabsContext'
export type { TabsListProps } from './TabsList'
export type { TabsTriggerProps } from './TabsTrigger'
export type { TabsPanelProps } from './TabsPanel'
